#!/usr/bin/env python3
"""
Build assets/content.js from assets/content/**.md

    python tools/build_content.py            # regenerate assets/content.js
    python tools/build_content.py --check    # fail if it is out of date

WHY A BUILD STEP RATHER THAN LOADING THE FILES DIRECTLY
-------------------------------------------------------
The site's README promises it opens straight from disk:

    Offline First: open the website directly in any browser using the file://
    protocol or host it easily on any static file server.

Under `file://` a browser refuses `fetch()` of local files, so a page that
loaded 59 markdown files at runtime would work when served and show nothing
when opened — breaking a documented feature and, worse, breaking it only for
the people who read the docs offline.

So the markdown files are the source you edit, and `assets/content.js` is a
generated artifact the browser loads with a plain `<script>` tag. No fetch, no
server requirement, no dependency — the project advertises none, and a docs
build is a poor place to introduce the first.

FRONTMATTER
-----------
Each page carries YAML frontmatter whose values are written as JSON strings:

    ---
    title: "Error handling"
    group: "The Cryo Language"
    lead: "`try` / `catch` / `finally`, `throw` and `assert`."
    ---

That is valid YAML — a double-quoted scalar — and it parses with `json.loads`,
so no YAML library is needed. A colon, a quote or a backslash in a title costs
nothing.

The page's **slug is its filename**. Nothing declares it twice, so nothing can
disagree about it.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONTENT = os.path.join(ROOT, 'assets', 'content')
NAV = os.path.join(CONTENT, '_nav.yaml')
OUT = os.path.join(ROOT, 'assets', 'content.js')

HEADER = """/* ============================================================
   Cryo · Burnout · Pyro documentation content.

   GENERATED — do not edit this file.
   Source: assets/content/<group>/<slug>.md   (order: assets/content/_nav.yaml)
   Rebuild: python tools/build_content.py

   Each `body` is markdown (rendered by assets/app.js) and is emitted as an
   array of lines joined by "\\n", so a body containing backticks or ${...}
   cannot terminate a template literal.
   ============================================================ */
"""


class BuildError(Exception):
    pass


def _scalar(raw: str, where: str):
    """A frontmatter value: JSON when quoted, otherwise the bare text."""
    raw = raw.strip()
    if not raw:
        return ''
    if raw[0] in '"[':
        try:
            return json.loads(raw)
        except json.JSONDecodeError as e:
            raise BuildError(f"{where}: value is not valid JSON ({e})")
    return raw


def read_page(path: str):
    """(meta, body) for one .md file. The slug is the filename."""
    with open(path, encoding='utf-8') as f:
        text = f.read()
    if not text.startswith('---'):
        raise BuildError(f"{os.path.basename(path)}: missing the --- frontmatter "
                         f"block. Every page needs at least a title.")
    end = text.find('\n---', 3)
    if end < 0:
        raise BuildError(f"{os.path.basename(path)}: the frontmatter block is "
                         f"never closed with ---")
    head = text[3:end]
    body = text[end + 4:].lstrip('\n')

    meta = {}
    for i, line in enumerate(head.split('\n'), start=2):
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if ':' not in line:
            raise BuildError(f"{os.path.basename(path)}:{i}: expected `key: value`")
        k, v = line.split(':', 1)
        meta[k.strip()] = _scalar(v, f"{os.path.basename(path)}:{i}")

    slug = os.path.splitext(os.path.basename(path))[0]
    if 'title' not in meta:
        raise BuildError(f"{slug}.md: no `title` in the frontmatter")
    meta['slug'] = slug
    return meta, body


def read_nav():
    """[(title, dir, [slug, ...])] in navigation order."""
    if not os.path.isfile(NAV):
        raise BuildError(f"missing {NAV}")
    groups, cur = [], None
    with open(NAV, encoding='utf-8') as f:
        for i, line in enumerate(f, start=1):
            s = line.strip()
            if not s or s.startswith('#'):
                continue
            if s.startswith('- title:'):
                cur = {'title': _scalar(s[len('- title:'):], f"_nav.yaml:{i}")}
                groups.append(cur)
            elif s.startswith('dir:') and cur is not None:
                cur['dir'] = _scalar(s[len('dir:'):], f"_nav.yaml:{i}")
            elif s.startswith('pages:') and cur is not None:
                cur['pages'] = _scalar(s[len('pages:'):], f"_nav.yaml:{i}")
            else:
                raise BuildError(f"_nav.yaml:{i}: unexpected line {s!r}")
    for g in groups:
        for k in ('dir', 'pages'):
            if k not in g:
                raise BuildError(f"_nav.yaml: group {g['title']!r} has no {k}")
    return groups


def js_lines(body: str) -> str:
    """The body as a JS array of JSON string literals, one per line."""
    # Drop exactly ONE trailing newline — the file's own terminator. Stripping
    # all of them would silently delete a blank line the page ends with;
    # stripping none would add one to every page.
    if body.endswith('\n'):
        body = body[:-1]
    lines = body.split('\n')
    return ',\n'.join('        ' + json.dumps(l, ensure_ascii=False)
                      for l in lines)


def build():
    nav = read_nav()
    out, seen, used = [], {}, set()

    for g in nav:
        d = os.path.join(CONTENT, g['dir'])
        if not os.path.isdir(d):
            raise BuildError(f"_nav.yaml names directory {g['dir']!r}, "
                             f"which does not exist")
        for slug in g['pages']:
            path = os.path.join(d, slug + '.md')
            if not os.path.isfile(path):
                raise BuildError(f"_nav.yaml lists {slug!r} in {g['dir']}, "
                                 f"but {g['dir']}/{slug}.md does not exist")
            meta, body = read_page(path)
            if slug in seen:
                raise BuildError(f"slug {slug!r} appears twice: "
                                 f"{seen[slug]} and {g['dir']}")
            seen[slug] = g['dir']
            used.add(os.path.normcase(path))
            if meta.get('group') and meta['group'] != g['title']:
                raise BuildError(
                    f"{slug}.md says group {meta['group']!r} but _nav.yaml "
                    f"lists it under {g['title']!r} — one of them is wrong, "
                    f"and the sidebar would use the nav")
            out.append((meta, body, g['title']))

    # A page nobody navigates to is invisible; that is almost always a
    # forgotten _nav.yaml entry rather than an intentional orphan.
    orphans = []
    for root, _dirs, files in os.walk(CONTENT):
        for name in files:
            if name.endswith('.md'):
                p = os.path.join(root, name)
                if os.path.normcase(p) not in used:
                    orphans.append(os.path.relpath(p, CONTENT))
    if orphans:
        raise BuildError(
            "these pages exist but are not listed in _nav.yaml, so nothing "
            "links to them:\n  - " + "\n  - ".join(sorted(orphans)))

    js = [HEADER, '(function () {', '  "use strict";',
          '  function md() { return Array.prototype.join.call(arguments, "\\n"); }',
          '', '  var pages = [']
    for meta, body, gtitle in out:
        js.append('    {')
        js.append(f'      slug: {json.dumps(meta["slug"], ensure_ascii=False)}, '
                  f'group: {json.dumps(gtitle, ensure_ascii=False)}, '
                  f'title: {json.dumps(meta["title"], ensure_ascii=False)},')
        if meta.get('lead'):
            js.append(f'      lead: {json.dumps(meta["lead"], ensure_ascii=False)},')
        js.append('      body: md(')
        js.append(js_lines(body))
        js.append('      )')
        js.append('    },')
    js.append('  ];')
    js.append('')
    js.append('  // Sidebar groups (order = navigation / pager order)')
    js.append('  var groups = [')
    for g in nav:
        js.append(f'    {{ title: {json.dumps(g["title"], ensure_ascii=False)}, '
                  f'pages: {json.dumps(g["pages"], ensure_ascii=False)} }},')
    js.append('  ];')
    js.append('')
    js.append('  window.DOCS = { pages: pages, groups: groups };')
    js.append('})();')
    return '\n'.join(js) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if assets/content.js is out of date')
    args = ap.parse_args()
    try:
        js = build()
    except BuildError as e:
        print(f"[docs] {e}", file=sys.stderr)
        return 1

    current = ''
    if os.path.isfile(OUT):
        with open(OUT, encoding='utf-8') as f:
            current = f.read()
    if args.check:
        if current != js:
            print("[docs] assets/content.js is out of date — "
                  "run: python tools/build_content.py", file=sys.stderr)
            return 1
        print("[docs] assets/content.js is up to date")
        return 0

    if current == js:
        print("[docs] assets/content.js already up to date")
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(js)
    pages = js.count('      body: md(')
    print(f"[docs] wrote assets/content.js — {pages} pages, {len(js)} bytes")
    return 0


if __name__ == '__main__':
    sys.exit(main())
